Create strings.xml
dessalines/jerboa pull request #1052
Opened 2023-07-17 12:32 UTC by Fish25op

Azerbaijani translations. It will be 100% completed later🥰

2023-07-17 13:05 UTC, MV-GH requested changes

2023-07-17 13:05 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_name" translatable="false">Jerboa</string>
Remove this one

2023-07-17 13:05 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_bars_dot_spacer">·</string>
Make the original not translatable, and remove all occurrences of this in the other translations.

2023-07-17 13:06 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="create_post_copy_suggested_title"> %1$s<> təklif olunan başlığı köçür</string>
Remove the <>

2023-07-17 13:21 UTC, Fish25op commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_name" translatable="false">Jerboa</string>
Why?
Whole?

2023-07-17 14:19 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_name">Jerboa</string>
Remove the entry not the attribute

2023-07-17 15:05 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_name" translatable>Jerboa</string>
No, I mean the whole string. When a entry isn't found in a translation it falls back to the default. So it isn't needed here. Same with all the English entries.

2023-07-17 15:17 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> -    <string name="app_bars_dot_spacer">·</string>
Mark the original default non translatable

2023-07-17 16:05 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_bars_dot_spacer">·</string>
No, i mean remove it here but modify the strings.xml in values to add the translatable="false"

2023-07-17 16:31 UTC, MV-GH commented on app/src/main/res/values-az/strings.xml
> +    <string name="app_bars_dot_spacer" translatable="false">·</string>
Almost there, now remove this line here and add it in values/strings.xml (replace the old line there)

2023-07-17 17:09 UTC, MV-GH commented
Remove `app_bars_dot_spacer` from all the other translations. Such as `values-da\strings.xml`. Then ill approve it.

2023-07-17 17:11 UTC, Fish25op commented
I didn't understand

2023-07-18 14:47 UTC, dessalines approved these changes

2023-07-18 14:48 UTC, merged