Adding the unblock option
dessalines/jerboa pull request #1171
Opened 2023-08-11 07:34 UTC by Schoolkid1

when a community is already blocked the else function should set the block to false

2023-08-11 07:47 UTC, MV-GH commented
It fails the formatting check, see https://github.com/dessalines/jerboa/blob/main/CONTRIBUTING.md, in this case you have to run `./gradlew formatKotlin`

2023-08-11 07:54 UTC, Schoolkid1 commented
Is there a specific prompt in which I can run this command, to be honest I don't know how to run that command in Android Studio...

2023-08-11 07:58 UTC, MV-GH commented
There is a terminal in android studio, run the above command in there. You can run it from any terminal/shell that has the repository as its working directory

2023-08-11 08:08 UTC, Schoolkid1 commented
I found the terminal it gives me the following feedback. Is there something wrong with my java?

  - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.2')
          - Variant 'sourcesElements' capability androidx.benchmark:benchmark-baseline-profile-gradle-plugin:1.2.0-alpha13 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library

2023-08-11 08:11 UTC, MV-GH commented
What java version are you using?

Follow this https://stackoverflow.com/questions/72117858/incompatible-because-this-component-declares-a-component-compatible-with-java-11

and set it to JDK 17

2023-08-11 08:18 UTC, Schoolkid1 commented
I am using java 8

The JDK version is 17.0.6 that should be sufficient right?

2023-08-11 08:32 UTC, MV-GH commented
Yeah i think that might be the problem, can you use java 17? or at least 11

2023-08-11 08:33 UTC, MV-GH commented
Also try this 
![image](https://github.com/dessalines/jerboa/assets/67873169/9bc6951d-d682-4e2e-b517-4addc50fd85c)

2023-08-11 08:56 UTC, Schoolkid1 commented
I updated my java but i still get the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:formatKotlinMain'.
> error formatting sources for formatKotlinMain

2023-08-11 09:05 UTC, MV-GH commented
Is that the full error? Can you run app in a emulator or you device?

2023-08-11 09:52 UTC, MV-GH commented
Your code doesn't compile, it can't format invalid code. Make sure it compiles first

2023-08-11 10:55 UTC, Schoolkid1 commented
I made some changes in the hope it does compile now, only i cannot check if it does from my laptop. Can you check if it does compile after this commit?

2023-08-11 11:07 UTC, Schoolkid1 commented
Can some one please check with me what is going wrong i am out of ideas at this point

2023-08-11 11:18 UTC, MV-GH commented
Why can't you check if it compiles from your laptop?

2023-08-11 11:34 UTC, Schoolkid1 commented
I really dont know.Normally i can use find usages on values and i see red lines when there is an error in the code but in this project i cannot use these features.  I think because the project is too big.

2023-08-11 11:35 UTC, MV-GH commented
Can you not press the run button at the top that tries to run the app? or build > make project?

2023-08-12 05:56 UTC, Schoolkid1 commented
I think it has to do with compatibility. But when im working on other apps the version is no problem

<img width="1271" alt="Screenshot 2023-08-12 at 07 55 48" src="https://github.com/dessalines/jerboa/assets/119050023/1a1be829-9e72-4a7f-a976-f973848b92c7">

2023-08-12 06:01 UTC, MV-GH commented
Ah you need to be using at least android studio Giraffe.

2023-08-13 09:26 UTC, Schoolkid1 commented
Thank you after updating i can finally run the app and gradle and look for bugs. I made some changes if you can check if it is sufficient at this point.

2023-08-13 20:36 UTC, MV-GH requested changes
Another thing I noticed is that you added this unblock functionality in the post options. But if the block is working properly the user would never come across any posts from that community and the user won't be able to unblock. For shortterm maybe for now you could show a short "snackbar" (popup with a button) after you block a community to unblock it. And longterm speaking we have to list somewhere all the communities a user has blocked where the user can unblock them.

2023-08-13 20:36 UTC, MV-GH commented on app/src/main/java/com/jerboa/api/Http.kt
> +    suspend fun unblockCommunity(@Body form: UnblockCommunity): Response<UnblockCommunityResponse>
There is no unblock API

2023-08-13 20:36 UTC, MV-GH commented on app/src/main/java/com/jerboa/datatypes/types/UnblockCommunity.kt
> +) : Parcelable
We didn't really document this well but all the datatypes are auto generated from the API backend. You don't need to make them manually, you just need to use the right one. In this case I think you need to use the blocked API but set the blocked field to false.

2023-08-13 20:36 UTC, MV-GH commented on app/src/main/java/com/jerboa/util/Initializable.kt
> +
Remove this line

2023-08-16 00:00 UTC, Schoolkid1 commented
Hey i saw there were some changes requested, my school project is finished but i would like to keep working. I committed the changes and it says the checks have been passed can you see if it is sufficient?

Also i see there is a import file that is conflicting, i guess that is still about the datatype class right? But I deleted that one, do you know why it still pops up?

2023-08-16 06:36 UTC, MV-GH commented
Your branch is behind with the main branch, both have changes in a similar file which is why you have conflicts. Update your forks main branch with  `git pull upstream main` *or press sync fork in github* and merge the changes from your main into this branch. It will give a conflict dialog which you will have to resolve.

2023-08-16 06:37 UTC, MV-GH commented on app/src/main/java/com/jerboa/api/Http.kt
> +    suspend fun unblockCommunity(@Body form: BlockCommunity): Response<BlockCommunityResponse>
Remove and just use the `blockCommunity` func

2023-08-17 21:40 UTC, Schoolkid1 commented
The requested changes are processed in the new commit.
I synced the fork as mentioned and got a pop-up with sync is successful, I did not get a conflict dialogue there.

2023-08-17 23:01 UTC, MV-GH commented
After you sync your fork you still need to merge the new changes from main into your Fork. I already did that for you now.

2023-08-22 17:42 UTC, dessalines commented
Still failing formatting.

2023-08-22 17:44 UTC, dessalines reviewed
This entire PR doesn't make any sense. If you've blocked a community, you will never see its posts or content to begin with after the initial block. This is why in lemmy-ui, you can only unblock communities from a section of your user settings, where you can view the communities you've blocked, and click an X to unblock them.

2023-08-22 17:46 UTC, dessalines commented
Closed in favor of #1185

2023-08-22 17:46 UTC, closed without merging