Fix the backspace bug by setting KeyboardType to 'Email'
dessalines/jerboa pull request #320
Opened 2023-02-09 17:37 UTC by Kradyz

A proposed approach to eliminate the backspace bug. Fixes #194 #148 

The autoCorrect is triggering the following undesirable behavior for text fields:

Given:

"Hello world <Cursor position>"

Pressing backspace two times will result in:

"Helloworl"

An attempt was made to turn autoCorrect off, but the approach failed because the KeyboardType.Text does not respect the autoCorrect = false setting. ([See documentation](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/KeyboardOptions#autoCorrect()))

The proposed solution is to change the KeyboardType to KeyboardType.Email, which does respect the autoCorrect = false setting.

I have tested this approach over a period of a few days. The backspace bug disappears, and I did not experience any negative effects from using the Email keyboard type. 

I looked into how to apply the autoCorrect = false setting to KeyboardType.Text, but I could not find how to do that.

2023-02-10 18:23 UTC, dessalines requested changes
Grep for `TextField(`, because there are a few more you missed here.

I'm seeing ones in `CommunityList.kt`, PostEdit.kt, CreatePost.kt, a few more in Login.kt, and InputFields.kt

Might also be good to create / use one in `InputFields.kt`, and just use that same simple one around.

2023-06-04 20:08 UTC, dessalines commented
@oscarnylander Do you have any experience with these strange keyboard autocorrect / backspace bugs ppl (including me) have been having with jetpack compose?

2023-06-04 20:19 UTC, oscarnylander commented
Unfortunately, no. I didn't encounter it during my time working professionally with Compose, and nowadays I only do Compose on the side.

2023-06-05 12:10 UTC, dessalines commented
Gotcha, thx!

2023-06-05 12:10 UTC, closed without merging