Fixed up ThemeMode enum to use strings in UI
dessalines/jerboa pull request #469
Opened 2023-06-09 00:51 UTC by a1studmuffin

Fixed up ThemeMode enum to use strings in "Look and Feel" settings UI (adds space to "System Black" theme mode)

2023-06-09 04:36 UTC, twizmwazin commented
I think this should wait on #447 so these strings can be included.

2023-06-09 18:58 UTC, dessalines approved these changes

2023-06-09 18:58 UTC, dessalines commented on app/src/main/java/com/jerboa/Utils.kt
> +    SystemBlack("System Black"),
Oops yeah, add these strings now to `strings.xml`

2023-06-09 18:59 UTC, dessalines requested changes
Oops yeah, add these strings now to strings.xml

2023-06-09 23:22 UTC, twizmwazin approved these changes

2023-06-10 00:12 UTC, dessalines approved these changes

2023-06-10 00:12 UTC, merged