Add setting to blur NSFW
dessalines/jerboa pull request #514
Opened 2023-06-11 04:31 UTC by TrollBlox

Accidentally deleted my old pull request. Please tell me if there is anything I should change.

* I will add an option to toggle from the lateral menu too, unless this is not something the creators want.

2023-06-11 21:10 UTC, TrollBlox commented
@twizmwazin My old PR was removed accidentally, this one replaced.

2023-06-12 06:08 UTC, twizmwazin requested changes

2023-06-12 06:08 UTC, twizmwazin commented on app/src/main/java/com/jerboa/MainActivity.kt
> +                            blur_setting = appSettings?.blurNSFW ?: true,
I think `blurNSFW` is better than `blur_setting`

2023-06-12 06:08 UTC, twizmwazin commented on app/src/main/java/com/jerboa/db/AppDB.kt
> +val MIGRATION_13_14 = object : Migration(13, 14) {
I think if these two features are grouped together than can be a single migration.

2023-06-12 06:08 UTC, twizmwazin commented on app/src/main/java/com/jerboa/ui/components/common/DrawerItems.kt
> +    val spacingMod = Modifier
Since this is just a single modifier I'm not sure it needs to be a value like this.

2023-06-12 06:09 UTC, twizmwazin commented
Also please rebase your changes!

2023-06-13 12:24 UTC, dessalines commented
Merge from main then we'll take another look.

2023-06-29 05:13 UTC, MV-GH commented
Closed, as is obsolete with #896

2023-06-29 05:13 UTC, closed without merging