add strings.xml for French
dessalines/jerboa pull request #638
Opened 2023-06-14 10:31 UTC by perepepepa

2023-06-14 13:22 UTC, dessalines commented
Lots of compile errors.

2023-06-17 05:58 UTC, perepepepa commented
Hi I fixed the compile errors and also some incorrect translations.
The errors were some unescaded apostrophies.
Now the pull request is stuck with woodpecker, it will unstuck by himself or I have to do something ?

2023-06-17 11:56 UTC, Krafting requested changes
Few tweaks

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="person_profile_report_person">Signaler utilisateur</string>
```suggestion
    <string name="person_profile_report_person">Signaler l'utilisateur</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="comment_mention_node_report_comment">Signaler commentaire</string>
```suggestion
    <string name="comment_mention_node_report_comment">Signaler le commentaire</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="community_community_info">Info communauté</string>
```suggestion
    <string name="community_community_info">Infos sur la communauté</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="community_block_community">Bloquer communauté</string>
```suggestion
    <string name="community_block_community">Bloquer la communauté</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="home_inbox">Boîte De Réception</string>
```suggestion
    <string name="home_inbox">Boîte de réception</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="home_add_account">Ajouter Un Profil</string>
```suggestion
    <string name="home_add_account">Ajouter un compte</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="inbox_inbox">Boîte De Réception</string>
```suggestion
    <string name="inbox_inbox">Boîte de réception</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="login_email_or_username">Courriel ou Nom Utilisateur</string>
```suggestion
    <string name="login_email_or_username">Courriel ou nom d'utilisateur</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="person_profile_block_person">Bloquer utilisateur</string>
```suggestion
    <string name="person_profile_block_person">Bloquer l'utilisateur</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="post_listing_new">( %1$s nuovi )</string>
```suggestion
    <string name="post_listing_new">( %1$s nouveau )</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="post_edit_body_placeholder">Contenuto</string>
```suggestion
    <string name="post_edit_body_placeholder">Contenu</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="create_post_a_title_here">un titre…</string>
```suggestion
    <string name="create_post_a_title_here">Un titre…</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="post_listing_copy_link">Copier lien</string>
```suggestion
    <string name="post_listing_copy_link">Copier le lien</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="post_listing_copy_permalink">Copier permalink</string>
```suggestion
    <string name="post_listing_copy_permalink">Copier le permalink</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="create_report_type_your_reason">Exprimer sa motivation</string>
```suggestion
    <string name="create_report_type_your_reason">Ecrivez la raison</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_display_name">Nom affiché</string>
```suggestion
    <string name="account_settings_display_name">Nom d'affichage</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="dialogs_all">Tout</string>
```suggestion
    <string name="dialogs_all">Tous</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_topyear">Meilleures de l\'Année</string>
```suggestion
    <string name="account_settings_topyear">Meilleures de l\'année</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_show_avatars">Afficher avatar</string>
```suggestion
    <string name="account_settings_show_avatars">Afficher les avatars</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_show_nsfw">Afficher NSFW</string>
```suggestion
    <string name="account_settings_show_nsfw">Afficher les publications NSFW</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_show_bot_accounts">Afficher compte bot</string>
```suggestion
    <string name="account_settings_show_bot_accounts">Afficher les comptes de robots</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="account_settings_bot_account">Compte bot</string>
```suggestion
    <string name="account_settings_bot_account">Compte de robot</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="look_and_feel_font_size">Taille De La Police : %1$s</string>
```suggestion
    <string name="look_and_feel_font_size">Taille de la police : %1$s</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="look_and_feel_theme_dark">Foncé</string>
```suggestion
    <string name="look_and_feel_theme_dark">Sombre</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="settings_activity_look_and_feel">Apparence interface</string>
```suggestion
    <string name="settings_activity_look_and_feel">Apparence de l'interface</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="comment_node_in">"in "</string>
```suggestion
    <string name="comment_node_in">"dans "</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="look_and_feel_activity_show_content_for_collapsed_comments">Afficher contenuto per commentaires minimizzati</string>
```suggestion
    <string name="look_and_feel_activity_show_content_for_collapsed_comments">Afficher le contenu des commentaires minimisés</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="comment_reply_node_copy_permalink">Copier Permalink</string>
```suggestion
    <string name="comment_reply_node_copy_permalink">Copier le permalink</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="person_profile_activity_posts">Publication</string>
```suggestion
    <string name="person_profile_activity_posts">Publications</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="bottomBar_inbox">Boîte De Réception</string>
```suggestion
    <string name="bottomBar_inbox">Boîte de réception</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="createPost_selectCommunity">Selectionner une communauté de la liste</string>
```suggestion
    <string name="createPost_selectCommunity">Selectionner une communauté dans liste</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="markdownHelper_insertLink">Inserer lien</string>
```suggestion
    <string name="markdownHelper_insertLink">Inserer un lien</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="markdownHelper_insertImage">Inserer image</string>
```suggestion
    <string name="markdownHelper_insertImage">Inserer une image</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="markdownHelper_insertQuote">Inserer citation</string>
```suggestion
    <string name="markdownHelper_insertQuote">Inserer une citation</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="markdownHelper_insertList">Inserer liste</string>
```suggestion
    <string name="markdownHelper_insertList">Inserer une liste</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="markdownHelper_insertHeader">Inserer titre</string>
```suggestion
    <string name="markdownHelper_insertHeader">Inserer un titre</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="voteToggle">Changer de Vote</string>
```suggestion
    <string name="voteToggle">Changer de vote</string>
```

2023-06-17 11:56 UTC, Krafting commented on app/src/main/res/values-fr/strings.xml
> +    <string name="look_and_feel_show_voting_arrows_list_view">Montrer le fleche de votation dans la liste</string>
```suggestion
    <string name="look_and_feel_show_voting_arrows_list_view">Montrer la fleche de vote dans la liste</string>
```

2023-06-19 12:22 UTC, merged