Show link dialog on long press
dessalines/jerboa pull request #651
Opened 2023-06-14 18:20 UTC by pipe01

When long pressing a post thumbnail or image a dialog will show containing actions related to the post's link, similar to Boost. If the link is an image, an option to download it will be added.

![image](https://github.com/dessalines/jerboa/assets/3885705/92f2138f-4f59-4376-a579-1158991b541f)

2023-06-14 20:13 UTC, MV-GH commented on app/src/main/java/com/jerboa/Utils.kt
> +    Toast.makeText(context, "Saved image", Toast.LENGTH_SHORT).show()
"Saved image" should be a stringResource

2023-06-14 21:50 UTC, twizmwazin requested changes
Please use string resources over literals, then it'll lgtm.

2023-06-15 12:04 UTC, dessalines commented on app/src/main/java/com/jerboa/Utils.kt
> +    Toast.makeText(context, "Saving image...", Toast.LENGTH_SHORT).show()
stringResource.

2023-08-20 21:11 UTC, MV-GH commented
Obsolete by #1189

2023-08-20 21:11 UTC, closed without merging