Nav scoped view models
dessalines/jerboa pull request #817
Opened 2023-06-22 13:56 UTC by nahwneeth

Since PR #765 was too big, splitting it up into multiple PR to make it easier to review.

# Scoped view models
- All the view models that were declared in the activity are now scoped to the routes in which they are used. View models used by most of the routes (like SiteViewModel, AccountViewModel & AccountSettingsViewModel) are left untouched.
- This prevents sharing view models that lead to stale data & reloading the data when navigating back.
- Making the LaunchedEffect run only once per route. This helps ensure that the content isn't reset with new data when moving back from one route to another. Things like scroll position & filters are also retained.
- Using extension function on navController to navigate in a type safe manner.

Closes #704
Closes #402 
Closes #774
Closes #835 

---

The following is the existing design where the view models reside in the `MainActivity` and are passed to all the activities:
![Untitled Diagram-Existing drawio](https://github.com/dessalines/jerboa/assets/55971921/28fbf265-b93a-401b-bdf7-3d225378c425)

---

The following is the design implemented by the PR:
![Untitled Diagram-PR drawio](https://github.com/dessalines/jerboa/assets/55971921/b6309f3c-127e-4870-a13b-807c56a82d4a)

- The channel is also a ViewModel that is scoped to the NavHost's nav graph which has `route = Route.Graph.ROOT`. This is created on the fly whenever you see something like `transferPostEditDepsViaRoot = navController.rootChannel<PostEditDeps>()`.
- Instead of initializing a global viewmodel and then navigating to it's activity. We store the dependencies in the global channel and then initialize the view model in it's respective activity.
- On success the updated data is put to the parent's back stack entry with a specific key (`PostEditReturn.POST_VIEW`) and then navigate back. On navigating back, the parent will recompose and we check if a value has been set in `PostEditReturn.POST_VEW` and update the post accordingly.

Other Notes:
- I've provided extensions to navigate to each activity. For eg. to navigate to PostEditActivity on has to call `navController.toPostEdit(Channel<PostView>, PostView)`. This way it's a compile time error to forget providing the dependencies necessary to initialize an activity.
- These deps are converted to JSON and rememberSaved in the respective route (when `navController.takeDepsFromRoot<PostView>()` is called). The updated data on the back stack entry's `SavedStateHandle` is also in JSON. Both survive process death.
- To reuse code, I've introduced abstractions like `InitializeRoute` and `ConsumeResult` which are self-explanatory.

2023-06-22 14:16 UTC, dessalines commented
It might be a while till I can go over bigger refactors like this.

2023-06-25 21:08 UTC, twizmwazin approved these changes
Would love to get this merged once rebased

2023-06-26 04:10 UTC, nahwneeth commented
Note regarding changes made while resolving merge conflicts:

- The user preferred sort & listing defaults were housed in HomeViewModel (PR #854). This has been moved to SiteViewModel. Reason: The CommunityActivity depended on HomeViewModel for the defaults which hinders scoping. Since, both already depended on SiteViewModel it made more sense to keep them there. Also, changing the filters in HomeActivity doesn't overwrite the user defaults. Would appreciate if @beatgammit reviewed these changes and pointed out if I missed out or overwrote any fixes.
- The PostCreate & PostEdit were consolidated (PR #860). I've tested the post edit and create functionality after rebasing and they seem to be working. Would appreciate if @sockenklaus reviewed these changes gave a thumbs up.

2023-06-26 04:54 UTC, twizmwazin requested changes

2023-06-26 04:54 UTC, twizmwazin commented on app/src/main/java/com/jerboa/MainActivity.kt
> -class MainActivity : AppCompatActivity() {
This needs to stay as AppCompatActivity for the in-app language picker

2023-06-26 04:54 UTC, twizmwazin commented on app/src/main/java/com/jerboa/ui/components/post/create/CreatePost.kt
This file is empty

2023-06-26 04:54 UTC, twizmwazin commented on app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
> +    homeViewModel: HomeViewModel,
I think there's sorta an unwritten convention where view models are kept towards the top of the argument lists for composable.

2023-06-26 04:54 UTC, twizmwazin commented on app/src/main/java/com/jerboa/MainActivity.kt
> -                        SwipeToNavigateBack(navController = navController) {
#785 added a gesture to swipe to close comments. It would be great if that could be maintained.

2023-06-26 05:34 UTC, sockenklaus commented
> Would appreciate if @sockenklaus reviewed these changes gave a thumbs up.

I'll gladly do and give it a look tonight.

2023-06-26 05:36 UTC, twizmwazin approved these changes

2023-06-26 07:17 UTC, nahwneeth commented
I've opened a new issue for the filters #886. For now, I've pushed a commit to ensure that the filters (in home & community activity) are read form the account variable. Ig we can continue with merging this PR and take up the filters thing separately. Any other issues with this branch, do let me know.

2023-06-26 14:05 UTC, sockenklaus reviewed
I only reviewed the files regarding post creation and editing because I honestly can't wrapt around my head about that amount of abstraction you added without investing a serious amount of time which I just don't have atm. (Hence my rather small PRs)
What I reviewed looked correct though and post creation and editing acted as expected.

2023-06-26 14:05 UTC, sockenklaus commented on app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt
> +        ) { postView ->
Again: Maybe use named parameter for onSuccess to increase readability?

2023-06-26 14:14 UTC, nahwneeth commented on app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt
> +    var name by rememberSaveable { mutableStateOf(postView.post.name) }
Now that the view models are scoped and declarative navigation is being used, the `PostEditActivity` can only be opened with a proper `PostView`. Perviously, the `pv` was taken from `PostViewModel` and no guarantees could be made that as postView was actually loaded and that's why all those null checks were required.

2023-06-26 14:22 UTC, nahwneeth commented
> What I reviewed looked correct though and post creation and editing acted as expected.
Thanks a lot for taking the time! Will make the changes you requested. 

I think that's the hard part, reviewing changes. I'll try to document these changes better.

2023-06-26 17:51 UTC, sockenklaus commented
> I think that's the hard part, reviewing changes. I'll try to document these changes better.

Thank you for further describing the changes you've made. I really appreciate your effort to make these changes as understandable as possible. 🙂

2023-06-26 22:00 UTC, merged

2023-09-01 04:19 UTC, MV-GH commented
I have question regarding `initializeRoute`, why did you take this approach over just having the necessary fields passed to the constructor of the ViewModel. Passing it in the constructor is much more typesafe as we now don't have to set each field as nullable that we have to check constantly

2023-09-01 04:45 UTC, nahwneeth commented
I was trying to keep the changes small in this PR since it was getting
harder to review. Other than the `initialized` field the view models don't
have any other changes.

Constructor initialization of view models is safer and we should try to do
that.



On Fri, 1 Sept, 2023, 9:49 am Maarten Vercruysse, ***@***.***>
wrote:

> I have question regarding initializeRoute, why did you take this approach
> over just having the necessary fields passed to the constructor of the
> ViewModel. Passing it in the constructor is much more typesafe as we now
> don't have to set each field as nullable that we have to check constantly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dessalines/jerboa/pull/817#issuecomment-1702133746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLBAUM4L76V4ATIW32RZGDXYFO5XANCNFSM6AAAAAAZQIAPA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-01 05:22 UTC, MV-GH commented
Thanks for your quick response, I'll make a issue for that and work on refactoring that

2023-09-01 17:26 UTC, MV-GH commented
I do have another question, 

For communityViewmodel you did this

```kt

val communityViewModel: CommunityViewModel = viewModel(
   remember(it) { navController.getBackStackEntry(Route.Graph.COMMUNITY) },
)

```

I am not sure what this does or why it exists? 

Why can it not be embedded in CommunityAcitivity?

2023-09-01 17:37 UTC, nahwneeth commented
navController.getBackStackEntry(Route.Graph.COMMUNITY)

This scopes the view model to the route with name Route.Graph.COMMUNITY

The community activity and community sidebar need to utilise the same view
model. I've made both these activities as subroutes of
Route.Graph.COMMUNITY.

So when creating a view model we don't scope it to the route but instead to
it's parent. When you navigate to the sidebar, it ends up using the view
model scoped to the parent.

So both community activity and community sidebar activity aren't embedded.

On Fri, 1 Sept, 2023, 10:56 pm Maarten Vercruysse, ***@***.***>
wrote:

> I do have another question,
>
> For communityViewmodel you did this
>
> val communityViewModel: CommunityViewModel = viewModel(
>    remember(it) { navController.getBackStackEntry(Route.Graph.COMMUNITY) },
> )
>
> I am not sure what this does or why it exists?
>
> Why can it not be embedded in CommunityAcitivity?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dessalines/jerboa/pull/817#issuecomment-1703093275>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLBAUJ222UYPDL2IPSQXFDXYILERANCNFSM6AAAAAAZQIAPA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-01 18:07 UTC, nahwneeth commented
Interesting. Give it a try. Make sure to put the addReturn lines within the
NavController.toCommunitySidebar() extension method. It should work and the
dependency is also explicit ig.

On Fri, 1 Sept, 2023, 11:30 pm Maarten Vercruysse, ***@***.***>
wrote:

> Hmm I see but I am thinking of simplifying this by just passing the
> CommunityView into Sidebar using the addReturn. Would a separate
> community_graph still be needed then?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dessalines/jerboa/pull/817#issuecomment-1703138688>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANLBAUM5S4NOAFCKKEAZPHDXYIPDPANCNFSM6AAAAAAZQIAPA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-01 18:39 UTC, MV-GH commented
Alright got it working, had to make a reverse addReturn/consumeReturn